package gui.debug;

import javafx.beans.property.BooleanProperty;
import javafx.beans.property.ReadOnlyBooleanProperty;
import javafx.beans.property.ReadOnlyObjectProperty;
import javafx.event.EventDispatcher;
import javafx.geometry.Bounds;
import javafx.geometry.NodeOrientation;
import javafx.geometry.Point3D;
import javafx.scene.*;
import javafx.scene.effect.BlendMode;
import javafx.scene.effect.Effect;
import javafx.scene.input.InputMethodRequests;
import javafx.scene.transform.Transform;

class NodeProperties {
    String                            accessibleHelp;
    String                            accessibleRoleDescription;
    AccessibleRole accessibleRole;
    String                            accessibleText;
    BlendMode blendMode;
    Bounds boundsInLocal;
    Bounds                            boundsInParent;
    CacheHint cacheHint;
    BooleanProperty cache;
    Node clip;
    Cursor cursor;
    DepthTest depthTest;
    ReadOnlyBooleanProperty disabled;
    BooleanProperty                   disable;
    NodeOrientation effectiveNodeOrientation;
    Effect effect;
    EventDispatcher eventDispatcher;
    ReadOnlyBooleanProperty           focused;
    BooleanProperty                   focusTraversable;
    ReadOnlyBooleanProperty           hover;
    String                            id;
    InputMethodRequests inputMethodRequests;
    ReadOnlyObjectProperty<Bounds> layoutBounds;
    double                            layoutX;
    double                            layoutY;
    Transform localToParentTransform;
    Transform                         localToSceneTransform;
    BooleanProperty                   managed;
    BooleanProperty                   mouseTransparent;
    NodeOrientation                   nodeOrientation;
    double                            opacity;
    Parent                            parent;
    BooleanProperty                   pickOnBounds;
    ReadOnlyBooleanProperty           pressed;
    double                            rotate;
    Point3D rotationAxis;
    double                            scaleX;
    double                            scaleY;
    double                            scaleZ;
    Scene                             scene;
    String                            style;
    double                            translateX;
    double                            translateY;
    double                            translateZ;
    BooleanProperty                   visible;

    public NodeProperties(Node node) {
        accessibleHelp                 = node.getAccessibleHelp();
        accessibleRoleDescription      = node.getAccessibleRoleDescription();
        accessibleRole                 = node.getAccessibleRole();
        accessibleText                 = node.getAccessibleText();
        blendMode                      = node.getBlendMode();
        boundsInLocal                  = node.getBoundsInLocal();
        boundsInParent                 = node.getBoundsInParent();
        cacheHint                      = node.getCacheHint();
        cache                          = node.cacheProperty();
        clip                           = node.getClip();
        cursor                         = node.getCursor();
        depthTest                      = node.getDepthTest();
        disabled                       = node.disabledProperty();
        disable                        = node.disableProperty();
        effectiveNodeOrientation       = node.getEffectiveNodeOrientation();
        effect                         = node.getEffect();
        eventDispatcher                = node.getEventDispatcher();
        focused                        = node.focusedProperty();
        focusTraversable               = node.focusTraversableProperty();
        hover                          = node.hoverProperty();
        id                             = node.getId();
        inputMethodRequests            = node.getInputMethodRequests();
        layoutBounds                   = node.layoutBoundsProperty();
        layoutX                        = node.getLayoutX();
        layoutY                        = node.getLayoutY();
        localToParentTransform         = node.getLocalToParentTransform();
        localToSceneTransform          = node.getLocalToSceneTransform();
        managed                        = node.managedProperty();
        mouseTransparent               = node.mouseTransparentProperty();
        nodeOrientation                = node.getNodeOrientation();
        opacity                        = node.getOpacity();
        parent                         = node.getParent();
        pickOnBounds                   = node.pickOnBoundsProperty();
        pressed                        = node.pressedProperty();
        rotate                         = node.getRotate();
        rotationAxis                   = node.getRotationAxis();
        scaleX                         = node.getScaleX();
        scaleY                         = node.getScaleY();
        scaleZ                         = node.getScaleZ();
        scene                          = node.getScene();
        style                          = node.getStyle();
        translateX                     = node.getTranslateX();
        translateY                     = node.getTranslateY();
        translateZ                     = node.getTranslateZ();
        visible                        = node.visibleProperty();
    }
}
